### ISSUE TITLE
Figma - Create the Introduction for a Type of Personality

### ISSUE THREAD

**Issue by SalazarGabrielAngelo-BSIT32E1** [ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1#17]
Create the Personality Type mock up design

Use either Canva or Figma (preferably) when creating the design.
Provide a link of the design and wait for evaluation,
It should contain the following:

- must have a introduction for that personality type
- must have a character image

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/d054206f-b6c5-403e-8985-0bf50b69e989)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/213f9b18-f4b7-4a8d-b1cb-260bd86147c2)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/b6fe6167-3a37-4328-a226-7b0a95a62738)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/241cc870-907d-4620-b451-142ec5bd1ac5)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/99395e07-1df5-4432-8a67-0de0da465731)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/46acfff9-bfb2-4653-b460-62ce9bc54b82)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/b6e26e11-8c5d-46d3-845e-811e4cbe7f74)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/81e32222-022f-4bc8-98c2-26b25fc2f539)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/df290cdf-aa9f-4ac7-9e2e-9c6f7ca567e8)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/c882300f-8a9f-4f36-b611-7c6b53ecc9d5)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/56b8a584-999c-4ea3-99b1-7e1ab8cf7665)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/c5a8ba87-205f-43b5-8d65-6aa89559588c)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/4d1cdddf-f3af-4968-bdd2-494aec82438c)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/d7161b04-87ab-40a1-b3fc-b1f101b6c819)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/6fbabb25-e03f-4739-9273-ab511cbccdbe)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/575b3fbf-acdc-4973-bd0a-ec05b9ef27c9)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/68440b6b-418e-4cea-a73c-467907d7888b)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/7208006c-c519-4a1d-92fc-53aa81c1cffa)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/5cd825dd-320a-4a4d-87c9-cbe60e10f338)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/8972b042-a979-48b1-b9b6-4008a37d5475)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/e0d9d524-8553-4369-95e6-798da839fcd1)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/6aa882a1-40fb-4bc3-b9db-84891294be84)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/42470875-3750-49bf-b6f2-d9546a4c65a4)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/778e5519-82f4-45e2-bb94-85f0b4432000)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/6983b2a3-ba11-45f3-b920-d864fc4dcace)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/b53f7452-9271-4231-98f5-d6776d7e782c)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/c9352a26-2e56-4ceb-a59f-0838763935b7)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/71498ec9-2199-45dd-8d9c-faeefe5b9ee4)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/098abb00-8563-40ed-87e2-f1606182d5a1)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/ffad4fab-58ac-4846-b209-03124a57fafd)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/a946e191-9f8f-4bc4-ad46-0810f17fea44)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/b3aebbc3-9dd6-4171-bc27-e8ed0d8c99f2)

**Comment by MonteroCharmVenice-BSIT32E1** [comment]
https://www.figma.com/design/fDYzOCgZHNo6WkkZu7JF5b/Untitled?node-id=16-26&t=t3CCAmPYOoROLBxX-0


![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160820060/4be5b64d-4a5e-4a5a-a271-1d414afc8f83)

**Comment by MonteroCharmVenice-BSIT32E1** [comment]
https://www.figma.com/design/fDYzOCgZHNo6WkkZu7JF5b/Untitled?node-id=17-57&t=t3CCAmPYOoROLBxX-0


![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160820060/6c85680b-3450-478d-9563-288a4fd73596)

**Comment by MonteroCharmVenice-BSIT32E1** [comment]
https://www.figma.com/design/fDYzOCgZHNo6WkkZu7JF5b/Untitled?node-id=21-98&t=t3CCAmPYOoROLBxX-0


![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160820060/3f11b920-d88f-45f1-92d9-7994b4a37b75)

**Comment by MonteroCharmVenice-BSIT32E1** [comment]
https://www.figma.com/design/fDYzOCgZHNo6WkkZu7JF5b/Untitled?node-id=21-100&t=t3CCAmPYOoROLBxX-0


![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160820060/7cfb2258-d4af-46b2-9f98-1c66d7858060)

**Comment by CantonjosArman-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160833955/219202b3-c7d8-49da-9779-1774dcc2a25c)

**Comment by SalazarGabrielAngelo-BSIT32E1** [comment]
@Sarmiento-Jerico-BSIT32E1 gawing transparent yung bg ng mga vectors also pa-add ng mga bg vectors

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/5be7a3b3-6850-4f2f-b697-97cc7f0ca41e)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/ae2526cf-9d33-47ee-a7ad-33703cd43b17)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/acfcfac2-d3ee-48a4-a14f-c72eabe27454)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/683ad216-786a-462c-b364-b6f9bd918b68)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/d97016cb-620a-4fb6-a92a-1128debbb7df)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/8cfc45c2-4752-49c1-bf0e-8c48c135cbcc)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/0096eac5-3820-4d4b-bac0-4cfd87a80590)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/17ae2e46-f2d4-461e-ba0c-7bd721ef6257)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/edb1ffbc-ec2e-4584-a8a4-b899eb045294)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/0eaffb36-8e74-42bd-b72e-ab2136e6060a)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/01d7db9d-4a76-4fdc-a9e4-90e211b282c1)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/77ba88e6-f1fa-40a9-b249-c7a7cc6db6f1)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/16279282-9457-417c-8234-1cb320ab7db3)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/425b9f02-a399-4ff6-bbdc-47ae886d8410)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/1a023314-0a6b-4867-a4d5-15aba1ebb6aa)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/590d1df7-c442-4ddf-b4cf-960103b50bf6)
