### ISSUE TITLE
Figma - Create the landing page for the quiz result

### ISSUE THREAD

**Issue by SalazarGabrielAngelo-BSIT32E1** [ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1#18]
Create  the landing page for the quiz result

example:
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/146562996/ab37433e-9c69-44a0-b3c3-b776ffd92ec7)

**Comment by Cresencio-RodolfoMiguel-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/148544502/d6bb85cc-a27d-4c8d-a6b1-55a4d36271f1)

**Comment by CantonjosArman-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160833955/6cbcb47a-473d-47cd-8b38-82d104e9d8dd)

**Comment by CantonjosArman-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160833955/3809a0bb-af3f-469e-9451-1cf4c971fb79)

**Comment by CantonjosArman-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160833955/7c852f9e-d828-401c-9325-2c9ffd88e946)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/361a9d8b-6446-4f2d-8bd1-7eb3bf95cc58)

**Comment by MonteroCharmVenice-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160820060/8391ab87-6c5a-4624-bf99-71517b040554)

**Comment by MonteroCharmVenice-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160820060/4de4f9bb-b962-41ec-82ff-a340e6d4eaab)

**Comment by MonteroCharmVenice-BSIT32E1** [comment]
https://www.figma.com/design/fDYzOCgZHNo6WkkZu7JF5b/Untitled?node-id=11-2&t=t3CCAmPYOoROLBxX-0


![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160820060/7c5ac41f-9245-467b-9fa4-fa13b1a9cceb)

**Comment by GarciaMarkAngelo-BSIT32E1** [comment]
> ![Image](https://private-user-images.githubusercontent.com/160833955/338302431-7c852f9e-d828-401c-9325-2c9ffd88e946.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzYyODgsIm5iZiI6MTcxODA3NTk4OCwicGF0aCI6Ii8xNjA4MzM5NTUvMzM4MzAyNDMxLTdjODUyZjllLWQ4MjgtNDAxYy05MzI1LTJjOWZmZDg4ZTk0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwMzE5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmJkNWRjNGExNGI3MGFmNWFhNWU5MzE4ZGYzZTg2M2YxMDdiNTJhMWQ2ZDllZTI4MWE2ZTM3YWRkMzg4ZGRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Iyl6i8lwjvbSdSusMcLrKoosuLDML9tVPwl1y7JPkUw)


Pa change naman ung contrast nung bg masakit masyado sa mata ung shade ng yellow na yan

**Comment by SalazarGabrielAngelo-BSIT32E1** [comment]
change the personality type to protagonist and remove the next button then add social media buttons and download button.

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
like ganito ba??

![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/a263e2ba-97f4-4cd0-a501-7b8926730e4b)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
noted editing rn

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
@SalazarGabrielAngelo-BSIT32E1  ito po?


![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/69e641f3-3bba-4ad9-bab1-083384f9f998)
