### ISSUE TITLE
Figma - Create an About page design - Draft

### ISSUE THREAD

**Issue by SalazarGabrielAngelo-BSIT32E1** [ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1#2]
Create the **About page** mock up design

- Use either Canva or Figma (preferably) when creating the design.
-  Provide a link of the design and wait for evaluation,

It should contain the following:
- **what is a personality test?**
- **who are the developers of the website and the roles?**
- **resources and references about the development.**

**Comment by CantonjosArman-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160833955/c430b187-0cdc-4b3f-9303-49c48c27839d)

**Comment by Rodrin-Johnpaul-B-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/161306927/d19937a5-fe9f-4c0e-b76c-7e735573f14f)

**Comment by Pajarillo-TerrenceJay-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/161125385/a0fee06f-3294-4be3-a746-673dd28d0ce4)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
okay noted send ko later

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/be65be00-9b99-4f73-b476-41b29971e79b)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/12ad8c6c-3e01-41c1-a877-0d955bf18eae)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/c8040ec7-0e79-43d9-8a6d-88bf8efc9a1f)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/0f251ded-5db7-4f98-beb8-614c0e65db6c)

**Comment by JOHNGABRIELROJAS** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/155618686/cd626424-723e-46fd-b70d-a4495ceaf28d)
