### ISSUE TITLE
Create Footer of the website

### ISSUE THREAD

**Issue by SalazarGabrielAngelo-BSIT32E1** [ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1#23]
Be sure to keep the color complementary to the website's color and inform the other members when you're done.

**Comment by SalazarGabrielAngelo-BSIT32E1** [comment]
https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/issues/3 

andito yung continuation ng design for each section ng website

**Comment by GerodiazRogel-BSIT32E1** [comment]
https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160821545/331a5585-c03b-405c-be69-0e98a93835a4

**Comment by GerodiazRogel-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160821545/99d2f984-8f96-48df-81e0-d1a7846e71c6)
