### ISSUE TITLE
Figma - Create the Personality type page - Draft

### ISSUE THREAD

**Issue by SalazarGabrielAngelo-BSIT32E1** [ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1#3]
Create the **Personality Type** mock up design

Use either Canva or **Figma** (preferably) when creating the design.
Provide a link of the design and wait for evaluation,
It should contain the following:

- **The 16 Personality types.**
- **A View that shows you the personality type you selected.**

**Comment by Belza-JanFelicity-BSIT32E1** [comment]
![1](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160820364/a3efced8-d99a-4fb8-984c-903ffca37345)

**Comment by Belza-JanFelicity-BSIT32E1** [comment]
![1 (1)](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160820364/8b75be75-b287-4e0c-8ff5-0f8f4acd53b0)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/518f3317-fd05-494a-9199-faade092320e)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/308c75a7-4c22-48cc-94d9-cdc6a18e5c47)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/4ae32dbc-9844-489f-8e0e-db438ea557e4)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/174705be-f09d-47ef-b536-2a06882988fd)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/000eb481-4b5f-4358-adea-cfcbd280937f)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/b85f4f83-d255-4f6f-9ea0-9a7ca91d6a11)

**Comment by CantonjosArman-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160833955/cc943048-5033-4cbb-8fc8-af115b958404)
