### ISSUE TITLE
Create the UI for Personality Types Introduction Page - Analyst Architect

### ISSUE THREAD

**Issue by GarciaMarkAngelo-BSIT32E1** [ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1#30]

**Comment by GarciaMarkAngelo-BSIT32E1** [comment]
For Reference:


![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160812645/b90bcac4-b390-499d-b9e2-d8e5fed60eec)

**Comment by SalazarGabrielAngelo-BSIT32E1** [comment]
for reference check yung wiki ni jj or yung backlog na ito: https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/issues/17

**Comment by TabinJasper-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/146046197/ca2615ba-7566-42da-93bb-74ff3b6fd595)

**Comment by TabinJasper-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/146046197/f884e0a6-0aa2-464f-9954-e0ba43d4964e)

**Comment by TabinJasper-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/146046197/b8a62181-a21a-46fe-a610-dd0538a10d6f)
