### ISSUE TITLE
Create a landing page for the result of the quiz

### ISSUE THREAD

**Issue by GarciaMarkAngelo-BSIT32E1** [ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1#31]
Objective:
Create a web page placeholder for the results.

Contents:

this will serve as the placeholder for the personality type the user gets where they can either print or share their results on their socials

updated version ng ui is eto: https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/issues/18

yung may like

example:

![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160812645/97d306d9-3c6c-4879-ba1c-ce93bc309038)

**Comment by SalazarGabrielAngelo-BSIT32E1** [comment]
updated version ng ui is eto: https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/issues/18

yung may like
