### ISSUE TITLE
Create the UI for Personality Types Introduction Page - Analyst Debater

### ISSUE THREAD

**Issue by GarciaMarkAngelo-BSIT32E1** [ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1#32]

**Comment by GarciaMarkAngelo-BSIT32E1** [comment]
For Reference:


![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160812645/2bff4576-d251-46df-a42a-25e1a4d766c5)

**Comment by SalazarGabrielAngelo-BSIT32E1** [comment]
for reference check yung wiki ni jj or yung backlog na ito: https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/issues/17

**Comment by TabinJasper-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/146046197/90061cc7-492c-498a-8137-3c07365eaa9d)

**Comment by TabinJasper-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/146046197/68bceb72-d896-44d9-9dfb-0f09795146ec)
