### ISSUE TITLE
Create the UI for Personality Types Introduction Page - Analyst Commander

### ISSUE THREAD

**Issue by SalazarGabrielAngelo-BSIT32E1** [ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1#39]
for reference check yung wiki ni jj or yung backlog na ito: https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/issues/17

**Comment by TabinJasper-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/146046197/053961a6-5b54-493b-8d3e-f8045f5149e6)

**Comment by TabinJasper-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/146046197/b1b1c287-f00e-4132-814a-8a39708acdbf)
