### ISSUE TITLE
Figma - Create a mockup design for the Quiz questions.

### ISSUE THREAD

**Issue by SalazarGabrielAngelo-BSIT32E1** [ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1#4]
Create a mock-up design for the questions

Goal:
**Try to make it as simple and easy on the eyes.**
**Add at least 5 questions on the design,**

**Comment by JOHNGABRIELROJAS** [comment]
![Draft question 1](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/155618686/1b810eeb-25be-46c9-b45a-cf220ca7e612)

**Comment by SalazarGabrielAngelo-BSIT32E1** [comment]
@JOHNGABRIELROJAS mali yung goodluck everyone papalitan ng next tsaka yung format ng questions is likert scale


parang ganito, pero i-base mo yung design mo dun sa na approved na (https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/issues/1)

![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/146562996/433c5048-9bbd-4818-8866-4dacbdcf5514)

**Comment by JOHNGABRIELROJAS** [comment]
![Uploading draft questioner.jpg…]()

**Comment by JOHNGABRIELROJAS** [comment]
![Uploading Draft question 1.jpg…]()

**Comment by JOHNGABRIELROJAS** [comment]
![Draft question 1](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/155618686/5d213cc1-a98b-42a8-8c75-e8f3cae21709)

**Comment by JOHNGABRIELROJAS** [comment]
![draft questioner](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/155618686/df28a41f-ae6c-4226-ba3b-5d005a09a1b3)

**Comment by Estrella-Ginmer-BSIT32E1** [comment]
[EWAN.pdf](https://githu@SalazarGabrielAngelo-BSIT32E1 .com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/files/15384309/EWAN.pdf)
@

**Comment by Estrella-Ginmer-BSIT32E1** [comment]
[Uploading EWAN.pdf…]()

**Comment by Estrella-Ginmer-BSIT32E1** [comment]
![ui](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/161201556/3f5da52a-a07e-4034-82ca-30386fc04c2c)

**Comment by MonteroCharmVenice-BSIT32E1** [comment]
https://www.figma.com/design/fDYzOCgZHNo6WkkZu7JF5b/Untitled?node-id=21-154&t=t3CCAmPYOoROLBxX-0


![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160820060/655b6710-fa59-4ac8-a24f-f9008cef55b5)
