### ISSUE TITLE
Create the UI for Personality Types Introduction Page - Analyst Logician

### ISSUE THREAD

**Issue by SalazarGabrielAngelo-BSIT32E1** [ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1#42]
for reference check yung wiki ni jj or yung backlog na ito: https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/issues/17

**Comment by TabinJasper-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/146046197/a3760ae3-e7ff-4a2a-a455-4378f6648541)

**Comment by TabinJasper-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/146046197/69126173-4d8b-48b9-a43a-4e887b06d156)

**Comment by TabinJasper-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/146046197/3fc26668-969e-4ea4-929e-c16d5901fde7)
