### ISSUE TITLE
Create Character Vectors for the Personality Types

### ISSUE THREAD

**Issue by GarciaMarkAngelo-BSIT32E1** [ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1#6]
Objective:
- Create (If possible) Character vector art for the 16 Personality Types. 
- The Characters must represent the personality type as stated in its description (e.g. ISTJ the Inspector should look like an inspector.)

**Comment by MonteroCharmVenice-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160820060/2176c2a5-e7db-47d9-9eac-6e7494fc98f9)

**Comment by MonteroCharmVenice-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160820060/f7d0bdee-1189-41f7-9022-b9bb43052592)

**Comment by GarciaMarkAngelo-BSIT32E1** [comment]
Asaan na ung mga gawa ng Iba?
iisa palang nagawa dito oh.

**Comment by Estrella-Ginmer-BSIT32E1** [comment]
![IMG_20240609_102513_545](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/161201556/5b5ffcac-7209-4994-aa55-7475132625b2)
![IMG_20240609_102511_233](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/161201556/bd142c5f-3602-474f-906d-ef4b3eb0c996)
![IMG_20240609_102509_573](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/161201556/40d5a889-ddeb-4b90-b71a-5b45cdae90a9)
![IMG_20240609_102507_300](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/161201556/69c4f533-c557-4571-b2a1-2aea448a3b0b)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/f49899ba-fa98-4b30-97c0-f58199d545f9)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/7247e7c8-3ecd-4432-9ddf-c7638891918a)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/e5c2538f-a504-427f-84e8-8c6aeef6e625)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/3ebf4086-c840-49c5-86b0-220aa5a5445a)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/a0682963-0e9d-410d-9cac-e572520678eb)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/790b45a3-eed6-46dd-bced-9415b329791d)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/8b000173-d6db-4713-9c5d-c40a329a372d)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/4019bab4-6bcc-4b8a-aef5-a05c4079f464)

**Comment by Sarmiento-Jerico-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/64b5b288-d8e6-47df-a8c5-7ecb2ca2b3ec)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/bc48a36b-1b36-4b34-85fc-45feea9005c8)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/d84429fe-07ce-4430-ab2a-ca1ffdab5953)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/ab390d5b-c14e-44bf-81fb-52e8c8c55aaa)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/93d9efc3-a728-4ffe-bb60-18240db386a7)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/c16f5a50-78a1-4818-a74c-c0fb1a3b1793)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/f099b0dc-d7ce-4c35-a0ca-f440e805534b)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/07e5cc41-9b7a-4737-a2ce-8e707f6faddb)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/0a0c0a1c-854d-4adb-9eb4-ab847b4fe86b)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/d9067c9b-919f-4120-9548-8d5a17432f59)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/3897fbf4-78c3-48fc-89bb-8192d7b97f67)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/7915cf76-3b65-416b-8769-fa2842371289)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/2784738e-4b01-4e42-8443-ed1218e9d92a)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/3dbc5e31-6677-4e62-a721-f6552bf6853a)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/3736c705-a696-47a5-b874-9cccc265fcae)
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/75025752/9e424cbf-3d0f-417e-bca5-596aee996f11)
