### ISSUE TITLE
Continuation Personality Type - Add the Bg for the personality type webpage

### ISSUE THREAD

**Issue by SalazarGabrielAngelo-BSIT32E1** [ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1#66]
https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/issues/3

refer to that link para sa bg ng webpage or sa wiki ni jj

**Comment by GerodiazRogel-BSIT32E1** [comment]
![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160821545/9e4261d2-b7ed-4916-a2bb-c19da76504f0)



![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160821545/a539ae1b-e98a-4a8a-8f47-e86d8d8703f8)



![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160821545/73ca0c00-e663-44ea-998d-c32a9afe2a4e)



![Image](https://github.com/ELEC2024-DEMACIANS-BSIT-32E1/ELEC2024_DEMACIANS_BSIT_32E1/assets/160821545/b44d5e79-875d-460e-a5eb-1f971b664ce9)
